# cut adaptor sequence in fq reads
for file in /public/home/tangkaifu/test_hu/rawdata/*;
do
cutadapt -g CGGCCAGTGAATTGTAATACGACTCACTATAGGGCGAATTGGGCCCGACGTCGCATGCTCCCGGCCGCCATGGCGGCCGCGGGAATTCGAT...ATCACTAGTGAATTCGCGGCCGCCTGCAGGTCGACCATATGGGAGAGCTCCCAACGCGTTGGATGCATAGCTTGAG  \
-g CTCAAGCTATGCATCCAACGCGTTGGGAGCTCTCCCATATGGTCGACCTGCAGGCGGCCGCGAATTCACTAGTGAT...ATCGAATTCCCGCGGCCGCCATGGCGGCCGGGAGCATGCGACGTCGGGCCCAATTCGCCCTATAGTGAGTCGTATTACAATTCACTGGCCG  \
-n 2 -e 0.1 -O 3 -m 10 -M 149  -o /public/home/tangkaifu/test_hu/process/1-cutadapt/$(basename $file .fq.gz).fq  $file \
> /public/home/tangkaifu/test_hu/process/1-cutadapt/1-$(basename $file .fq.gz)_cutadapt.txt; \
done